### ISSUE TITLE
Revisar Desafio de Arrays

### ISSUE THREAD

**Issue by Kacaii** [Eloi-0001/CoDing01#2]
## Revisão e Teste

Não tenho certeza se o código  que fizemos em sala funciona.

## TODO List

- [x] Adicionar o código no github.
- [x] Revisar o código e procurar por erros em potencial.
- [x] Corrijir os erros.
- [x] Testar o código novo e verificar se funciona.
